/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

/**
 * Minimal DXF R2000 (AC1015) writer: layers with ACI colour, lineweight and
 * linetype, and LINE / LWPOLYLINE / TEXT in model space. Everything else comes
 * from a fixed template generated by ezdxf (see sjabloon-r2000.gen.ts), so
 * the structural bookkeeping AutoCAD is strict about is not hand-written here.
 */

import {
  SJABLOON_HANDSEED, SJABLOON_MODELSPACE, SJABLOON_PLOTSTIJL, SJABLOON_R2000,
} from './sjabloon-r2000.gen.js';

export interface Punt { x: number; y: number }

/** Lineweight in hundredths of a millimetre (DXF group 370), e.g. 50 = 0,50 mm. */
export type Lijndikte = 0 | 5 | 9 | 13 | 15 | 18 | 20 | 25 | 30 | 35 | 40 | 50 | 53 | 60 | 70 | 80 | 90 | 100;

export type Lijntype = 'Continuous' | 'DASHED';

export interface TekstOpties {
  rotatieGraden?: number;
  /** 0 left, 1 centre, 2 right. */
  horizontaal?: 0 | 1 | 2;
  /** 0 baseline, 1 bottom, 2 middle, 3 top. */
  verticaal?: 0 | 1 | 2 | 3;
}

const getal = (v: number): string => {
  if (!Number.isFinite(v)) throw new Error(`DXF: ongeldige coördinaat ${v}`);
  // 6 decimals = 1 nm in mm drawings; strip trailing zeros for compact files.
  const s = v.toFixed(6);
  return s.includes('.') ? s.replace(/0+$/, '').replace(/\.$/, '.0') : s;
};

/** DXF layer names may not contain <>/\":;?*|=` and are max 255 chars. */
export function veiligeLaagnaam(naam: string): string {
  const s = naam.replace(/[<>/\\":;?*|=`]/g, '_').trim();
  return (s || 'LAAG').slice(0, 255);
}

/** Drawing unit and its DXF $INSUNITS code. */
export type Eenheid = 'mm' | 'cm' | 'm';
export const INSUNITS: Readonly<Record<Eenheid, number>> = { mm: 4, cm: 5, m: 6 };

export class DxfR2000 {
  /**
   * @param streep dash and gap of the DASHED linetype, in drawing units. The
   *   template's own pattern (20 / 10) is meant for paper-size drawings and
   *   reads as a solid line on a building drawn in millimetres.
   */
  constructor(
    private readonly eenheid: Eenheid = 'mm',
    private readonly streep: { streep: number; gat: number } = { streep: 200, gat: 100 },
  ) {}

  private volgende = parseInt(SJABLOON_HANDSEED, 16);
  private lagen = new Map<string, string>();
  private entiteiten: string[] = [];
  private min = { x: Infinity, y: Infinity };
  private max = { x: -Infinity, y: -Infinity };

  private handle(): string {
    return (this.volgende++).toString(16).toUpperCase();
  }

  private omvat(p: Punt): void {
    this.min = { x: Math.min(this.min.x, p.x), y: Math.min(this.min.y, p.y) };
    this.max = { x: Math.max(this.max.x, p.x), y: Math.max(this.max.y, p.y) };
  }

  /** Declare (or look up) a layer; returns the sanitized name to use. */
  laag(naam: string, aci: number, lijndikte: Lijndikte, lijntype: Lijntype = 'Continuous'): string {
    const veilig = veiligeLaagnaam(naam);
    if (veilig === '0' || this.lagen.has(veilig)) return veilig;
    const kleur = Number.isInteger(aci) && aci >= 1 && aci <= 255 ? aci : 7;
    this.lagen.set(veilig, [
      '0', 'LAYER', '5', this.handle(), '330', '1',
      '100', 'AcDbSymbolTableRecord', '100', 'AcDbLayerTableRecord',
      '2', veilig, '70', '0', '62', String(kleur), '6', lijntype,
      '370', String(lijndikte), '390', SJABLOON_PLOTSTIJL,
    ].join('\n'));
    return veilig;
  }

  private kop(type: string, laag: string, subklasse: string): string[] {
    return ['0', type, '5', this.handle(), '330', SJABLOON_MODELSPACE,
      '100', 'AcDbEntity', '8', laag, '100', subklasse];
  }

  lijn(a: Punt, b: Punt, laag: string): void {
    this.omvat(a); this.omvat(b);
    this.entiteiten.push([...this.kop('LINE', laag, 'AcDbLine'),
      '10', getal(a.x), '20', getal(a.y), '30', '0.0',
      '11', getal(b.x), '21', getal(b.y), '31', '0.0'].join('\n'));
  }

  /** Polyline; `bulges[i]` (optional) is the arc bulge from vertex i to i+1. */
  polylijn(punten: Punt[], gesloten: boolean, laag: string, bulges?: number[]): void {
    if (punten.length < 2) return;
    const g = [...this.kop('LWPOLYLINE', laag, 'AcDbPolyline'),
      '90', String(punten.length), '70', gesloten ? '1' : '0', '43', '0.0'];
    punten.forEach((p, i) => {
      this.omvat(p);
      g.push('10', getal(p.x), '20', getal(p.y));
      const b = bulges?.[i];
      if (b) g.push('42', getal(b));
    });
    this.entiteiten.push(g.join('\n'));
  }

  tekst(p: Punt, hoogte: number, waarde: string, laag: string, opties: TekstOpties = {}): void {
    this.omvat(p);
    const h = opties.horizontaal ?? 0;
    const v = opties.verticaal ?? 0;
    const uitgelijnd = h !== 0 || v !== 0;
    const g = [...this.kop('TEXT', laag, 'AcDbText'),
      '10', getal(p.x), '20', getal(p.y), '30', '0.0',
      '40', getal(hoogte), '1', tekstwaarde(waarde)];
    if (opties.rotatieGraden) g.push('50', getal(opties.rotatieGraden));
    if (h) g.push('72', String(h));
    if (uitgelijnd) g.push('11', getal(p.x), '21', getal(p.y), '31', '0.0');
    g.push('100', 'AcDbText');
    if (v) g.push('73', String(v));
    this.entiteiten.push(g.join('\n'));
  }

  toString(): string {
    let t = SJABLOON_R2000;
    const vervang = (zoek: string, door: string): void => {
      const i = t.indexOf(zoek);
      if (i < 0 || t.indexOf(zoek, i + 1) >= 0) throw new Error(`DXF-sjabloon: marker niet uniek: ${zoek}`);
      t = t.slice(0, i) + door + t.slice(i + zoek.length);
    };
    const lagen = [...this.lagen.values()];
    // Layer table: entry count + our records after the template's own layers.
    const tabelKop = '\n  2\nLAYER\n  5\n1\n330\n0\n100\nAcDbSymbolTable\n 70\n2\n';
    vervang(tabelKop, tabelKop.replace(' 70\n2\n', ` 70\n${2 + lagen.length}\n`));
    if (lagen.length) {
      const i = t.indexOf('\n  0\nENDTAB\n', t.indexOf('AcDbLayerTableRecord'));
      t = `${t.slice(0, i)}\n${lagen.map(normaliseer).join('\n')}${t.slice(i)}`;
    }
    if (this.entiteiten.length) {
      vervang('\nENTITIES\n  0\nENDSEC\n', `\nENTITIES\n${this.entiteiten.map(normaliseer).join('\n')}\n  0\nENDSEC\n`);
    }
    if (Number.isFinite(this.min.x)) {
      vervang('$EXTMIN\n 10\n1e+20\n 20\n1e+20\n 30\n1e+20\n',
        `$EXTMIN\n 10\n${getal(this.min.x)}\n 20\n${getal(this.min.y)}\n 30\n0.0\n`);
      vervang('$EXTMAX\n 10\n-1e+20\n 20\n-1e+20\n 30\n-1e+20\n',
        `$EXTMAX\n 10\n${getal(this.max.x)}\n 20\n${getal(this.max.y)}\n 30\n0.0\n`);
    }
    vervang('$INSUNITS\n 70\n4\n', `$INSUNITS\n 70\n${INSUNITS[this.eenheid]}\n`);
    const { streep, gat } = this.streep;
    if (!(streep > 0 && gat > 0)) throw new Error(`DXF: ongeldig streeppatroon ${streep}/${gat}`);
    vervang(' 40\n30.0\n 49\n20.0\n 74\n0\n 49\n-10.0\n 74\n0\n',
      ` 40\n${getal(streep + gat)}\n 49\n${getal(streep)}\n 74\n0\n 49\n${getal(-gat)}\n 74\n0\n`);
    vervang(`$HANDSEED\n  5\n${SJABLOON_HANDSEED}\n`, `$HANDSEED\n  5\n${this.handle()}\n`);
    return t;
  }
}

/**
 * The file is written as UTF-8 but an R2000 reader decodes it with
 * $DWGCODEPAGE (ANSI_1252), so every non-ASCII character goes out as the
 * DXF escape \U+XXXX.
 */
function tekstwaarde(waarde: string): string {
  return waarde.replace(/[\r\n]+/g, ' ').replace(/[^\x20-\x7e]/gu, (c) =>
    `\\U+${c.codePointAt(0)!.toString(16).toUpperCase().padStart(4, '0')}`);
}

/** Group codes right-aligned to 3 characters, like the template. */
function normaliseer(blok: string): string {
  const r = blok.split('\n');
  for (let i = 0; i < r.length; i += 2) r[i] = r[i].padStart(3, ' ');
  return r.join('\n');
}
